//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intel.SPEED.Module.Web.IlmDivSubscription.controls {
    
    
    public partial class ilm_div_subscription_fields {
        
        /// <summary>
        /// rptSubscriptionFields control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportExt rptSubscriptionFields;
        
        /// <summary>
        /// td_label_left control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt td_label_left;
        
        /// <summary>
        /// ele_label_left control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element ele_label_left;
        
        /// <summary>
        /// ele_col_idn_left control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element ele_col_idn_left;
        
        /// <summary>
        /// ele_col_nme_left control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element ele_col_nme_left;
        
        /// <summary>
        /// td_field_left control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt td_field_left;
        
        /// <summary>
        /// ele_obj_left control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ControlContainer ele_obj_left;
        
        /// <summary>
        /// td_space control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt td_space;
        
        /// <summary>
        /// td_label_right control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt td_label_right;
        
        /// <summary>
        /// ele_label_right control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element ele_label_right;
        
        /// <summary>
        /// ele_col_idn_right control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element ele_col_idn_right;
        
        /// <summary>
        /// ele_col_nme_right control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element ele_col_nme_right;
        
        /// <summary>
        /// td_field_right control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt td_field_right;
        
        /// <summary>
        /// ele_obj_right control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ControlContainer ele_obj_right;
    }
}
