//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intel.SPEED.Module.Web.IlmDivSubscription.controls {
    
    
    public partial class ilm_div_subscription_notif_list {
        
        /// <summary>
        /// rptSubscription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportExt rptSubscription;
        
        /// <summary>
        /// subject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt subject;
        
        /// <summary>
        /// eleSubject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleSubject;
        
        /// <summary>
        /// processed_dte control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt processed_dte;
        
        /// <summary>
        /// eleProcessDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleProcessDate;
    }
}
