//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intel.SPEED.Module.Web.IlmDivSubscription.controls {
    
    
    public partial class ilm_div_subscription_list {
        
        /// <summary>
        /// btnScbListEditCol control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ButtonExt2 btnScbListEditCol;
        
        /// <summary>
        /// rptSubscriptionList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportExt rptSubscriptionList;
        
        /// <summary>
        /// div_start_dte control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_start_dte;
        
        /// <summary>
        /// eleStartDte control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleStartDte;
        
        /// <summary>
        /// div_orig_usr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_orig_usr;
        
        /// <summary>
        /// eleOrigUsr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleOrigUsr;
        
        /// <summary>
        /// div_iss_src control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_iss_src;
        
        /// <summary>
        /// eleIssSrc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleIssSrc;
        
        /// <summary>
        /// div_exc_typ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_exc_typ;
        
        /// <summary>
        /// eleExcTyp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleExcTyp;
        
        /// <summary>
        /// div_prod_cls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_prod_cls;
        
        /// <summary>
        /// dleProdCls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element dleProdCls;
        
        /// <summary>
        /// div_lvl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_lvl;
        
        /// <summary>
        /// eleLvl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleLvl;
        
        /// <summary>
        /// div_symp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_symp;
        
        /// <summary>
        /// eleSymp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleSymp;
        
        /// <summary>
        /// div_plc_phs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_plc_phs;
        
        /// <summary>
        /// elePlcPhs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element elePlcPhs;
        
        /// <summary>
        /// div_prod_fmly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_prod_fmly;
        
        /// <summary>
        /// eleProdFmly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleProdFmly;
        
        /// <summary>
        /// div_bus_unit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_bus_unit;
        
        /// <summary>
        /// eleBusUnit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleBusUnit;
        
        /// <summary>
        /// div_risk_scre control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_risk_scre;
        
        /// <summary>
        /// eleRiskScre control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleRiskScre;
        
        /// <summary>
        /// div_prim_rc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_prim_rc;
        
        /// <summary>
        /// elePrimRc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element elePrimRc;
        
        /// <summary>
        /// div_sub_rc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_sub_rc;
        
        /// <summary>
        /// eleSubRc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleSubRc;
        
        /// <summary>
        /// div_escp_pnt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_escp_pnt;
        
        /// <summary>
        /// eleEscpPnt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleEscpPnt;
        
        /// <summary>
        /// div_svr_type control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_svr_type;
        
        /// <summary>
        /// eleSvrType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleSvrType;
        
        /// <summary>
        /// div_status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_status;
        
        /// <summary>
        /// eleStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleStatus;
        
        /// <summary>
        /// div_pblm_owner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_pblm_owner;
        
        /// <summary>
        /// elePblmOwner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element elePblmOwner;
        
        /// <summary>
        /// div_clsure_aprvr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_clsure_aprvr;
        
        /// <summary>
        /// eleClsureAprvr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleClsureAprvr;
        
        /// <summary>
        /// div_linked_prt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_linked_prt;
        
        /// <summary>
        /// eleLinkedPrt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleLinkedPrt;
        
        /// <summary>
        /// div_linked_cirs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_linked_cirs;
        
        /// <summary>
        /// eleLinkedCirs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleLinkedCirs;
        
        /// <summary>
        /// div_linked_qan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_linked_qan;
        
        /// <summary>
        /// delLinkedQan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element delLinkedQan;
        
        /// <summary>
        /// alrt_typ_idn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt alrt_typ_idn;
        
        /// <summary>
        /// eleAlrtTyp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Element eleAlrtTyp;
        
        /// <summary>
        /// div_scb_idn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ReportColExt div_scb_idn;
        
        /// <summary>
        /// hdnScbIdn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.HiddenExt2 hdnScbIdn;
    }
}
