//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intel.SPEED.Module.Web.IlmDivSubscription.pages {
    
    
    public partial class ilm_div_subscription_notif_list {
    }
}
