//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intel.SPEED.Module.Web.IlmDivSubscription.pages {
    
    
    public partial class ilm_div_subscription {
        
        /// <summary>
        /// hdnSubscriptionId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.HiddenExt2 hdnSubscriptionId;
        
        /// <summary>
        /// hdnHierarchyEnforced control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.HiddenExt2 hdnHierarchyEnforced;
        
        /// <summary>
        /// hdnCcUserFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.HiddenExt2 hdnCcUserFlag;
        
        /// <summary>
        /// hdnCcUserEnv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.HiddenExt2 hdnCcUserEnv;
        
        /// <summary>
        /// speedFrameSubscription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.SpeedFrame speedFrameSubscription;
        
        /// <summary>
        /// pnlSubscriptionFields control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.Panel pnlSubscriptionFields;
        
        /// <summary>
        /// btnCreateNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ButtonExt2 btnCreateNew;
        
        /// <summary>
        /// btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ButtonExt2 btnSave;
        
        /// <summary>
        /// btnDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ButtonExt2 btnDelete;
        
        /// <summary>
        /// ctrlFields control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Module.Web.IlmDivSubscription.controls.ilm_div_subscription_fields ctrlFields;
        
        /// <summary>
        /// btnCreateNewBottom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ButtonExt2 btnCreateNewBottom;
        
        /// <summary>
        /// btnSaveBottom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ButtonExt2 btnSaveBottom;
        
        /// <summary>
        /// btnDeleteBottom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.ButtonExt2 btnDeleteBottom;
        
        /// <summary>
        /// pnlSubscriptionList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Core.Web.Control.Extension.Panel pnlSubscriptionList;
        
        /// <summary>
        /// ctrlSubscriptionList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intel.SPEED.Module.Web.IlmDivSubscription.controls.ilm_div_subscription_list ctrlSubscriptionList;
    }
}
